### ISSUE TITLE
smock run能够生成一份静态的mock数据文件吗？

### ISSUE THREAD

**Issue by sjoooo123** [jdf2e/SMock#1]
运行smock run开启服务之后，前端直接调用服务提供的mock数据，数据是实时生成的；
请问想保留一份静态数据，直接调用，不用实时生成，能做到吗？

**Comment by shelly0702** [comment]
> 运行smock run开启服务之后，前端直接调用服务提供的mock数据，数据是实时生成的；
> 请问想保留一份静态数据，直接调用，不用实时生成，能做到吗？

用实时生成主要是考虑到后端变动了swagger文档后，前端不知道，所以会实时生成。
如果想要保留一份静态数据的话，先可以从生成的模拟数据文件夹中去拷贝一份出来。
后面我们再加入是否实时更新数据的开关在其中。感谢您的反馈

**Comment by sjoooo123** [comment]
生成的模拟数据文件是这样的，感觉不能用啊， 
![image](https://user-images.githubusercontent.com/22810581/48884336-08199c00-ee5f-11e8-97ab-f5a6e8e20070.png)，
我希望返回的数据是：
![image](https://user-images.githubusercontent.com/22810581/48884356-1ff12000-ee5f-11e8-831c-9054a59fc5cd.png)，请问我的配置是不是哪里写错了？

**Comment by sjoooo123** [comment]
不好意思，还有个疑问，生成的模拟数据文件里面的数据是这样的，
![image](https://user-images.githubusercontent.com/22810581/48885393-136ec680-ee63-11e8-86d2-39324ad15099.png)，
字符串统一都是'string'，数字都是0，感觉这样的静态数据，能直接用吗？

**Comment by codeSnipe** [comment]
暂时我们使用的是swagger中提供的假数据。
mock数据中内容，我们有计划自动随机创建，但内容数据动态化，依旧会感觉可能有点假。
如String类型，我们可能会随机抽取文字拼装，有可能不是一句话，不过这样可以提供给使用者，不同接口的使用体验。后续我们会针对此内容进行更新，感谢提供的好建议。

**Comment by sjoooo123** [comment]
目前项目中也是用的这样的假数据吗？感觉这样基本不能用呢；期待内容数据动态化，即使有点假，也比现在的好吧，至少能够用起来就行。
