### ISSUE TITLE
能否集成docker

### ISSUE THREAD

**Issue by lokinell** [jdf2e/SMock#3]
我觉得，可以和Swagger editor，docker集成来弄一个docker image，让使用者可以快速构建一个公用的mock api接口环境。

**Comment by codeSnipe** [comment]
嗯，如果这个集成到docker里面的话也是一种多人协同的方式，无需重复的抓取数据，这个会在后续的计划中进行尝试，这个如果作为开源对外部使用的话，docker方式会需要使用的团队具备搭建docker smock环境的能力，或者我们提供docker服务器面向外部。其实这样做的话，SMock逐渐的就会变成一个平台性质了，感觉后续的扩展性以及变动性会被拘束。
