### ISSUE TITLE
既然能拿到接口定义，是不是可以直接根据接口类型生成接口调用的代码？

### ISSUE THREAD

**Issue by loveky** [jdf2e/SMock#5]
听完昨天分享的一点思考。既然能拿到 接口地址，参数，get/post，那是不是可以直接生成一个 `api.js`

用户可以直接`import` 进来调取后端数据了。

一点想法，仅供参考

**Comment by codeSnipe** [comment]
现在已经生成了一份API的文件列表，支持UMD，没支持es6 module，后续可以根据配置来切换生成的api.js的模块模式。
